basic/music/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('basic.music.views',
    url(r'^genres/(?P<slug>[-\w]+)/$',
        view='genre_detail',
        name='music_genre_detail',
    ),
    url (r'^genres/$',
        view='genre_list',
        name='music_genre_list',
    ),
    url(r'^labels/(?P<slug>[-\w]+)/$',
        view='label_detail',
        name='music_label_detail',
    ),
    url (r'^labels/$',
        view='label_list',
        name='music_label_list',
    ),
    url(r'^bands/(?P<slug>[-\w]+)/$',
        view='band_detail',
        name='music_band_detail',
    ),
    url (r'^bands/$',
        view='band_list',
        name='music_band_list',
    ),
    url(r'^albums/(?P<slug>[-\w]+)/$',
        view='album_detail',
        name='music_album_detail',
    ),
    url (r'^albums/$',
        view='album_list',
        name='music_album_list',
    ),
    url(r'^tracks/(?P<slug>[-\w]+)/$',
        view='track_detail',
        name='music_track_detail',
    ),
    url (r'^tracks/$',
        view='track_list',
        name='music_track_list',
    ),
)


urlpatterns += patterns('',
    url (r'^$',
        view='django.views.generic.simple.direct_to_template',
        kwargs={'template': 'music/index.html'},
        name='music_index',
    ),
)

basic/music/models.py
from django.db import models
from django.db.models import permalink
from django.conf import settings
from basic.people.models import Person


class Genre(models.Model):
    """Genre model"""
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'music_genres'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('music_genre_detail', None, { 'slug': self.slug })


class Label(models.Model):
    """Label model"""
    title = models.CharField(max_length=100)
    prefix = models.CharField(max_length=20, blank=True)
    slug = models.SlugField(unique=True)
    website = models.URLField(blank=True)

    class Meta:
        db_table = 'music_labels'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.full_title

    @property
    def full_title(self):
        return '%s %s' % (self.prefix, self.title)

    @permalink
    def get_absolute_url(self):
        return ('music_label_detail', None, { 'slug': self.slug })


class Band(models.Model):
    """Band model"""
    title = models.CharField(max_length=100)
    prefix = models.CharField(max_length=20, blank=True)
    slug = models.SlugField(unique=True)
    musicians = models.ManyToManyField(Person, blank=True, limit_choices_to={'person_types__slug__exact': 'musician'})
    website = models.URLField(blank=True)

    class Meta:
        db_table = 'music_bands'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.full_title

    @property
    def full_title(self):
        return '%s %s' % (self.prefix, self.title)

    @permalink
    def get_absolute_url(self):
        return ('music_band_detail', None, { 'slug': self.slug })


class Album(models.Model):
    """Album model"""
    title = models.CharField(max_length=255)
    prefix = models.CharField(max_length=20, blank=True)
    subtitle = models.CharField(blank=True, max_length=255)
    slug = models.SlugField()
    band = models.ForeignKey(Band, blank=True)
    label = models.ForeignKey(Label, blank=True)
    asin = models.CharField(max_length=14, blank=True)
    release_date = models.DateField(blank=True, null=True)
    cover = models.FileField(upload_to='albums', blank=True)
    review = models.TextField(blank=True)
    genre = models.ManyToManyField(Genre, blank=True)
    is_ep = models.BooleanField(default=False)
    is_compilation = models.BooleanField(default=False)

    class Meta:
        db_table = 'music_albums'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.full_title

    @permalink
    def get_absolute_url(self):
        return ('music_album_detail', None, { 'slug': self.slug })

    @property
    def full_title(self):
        return '%s %s' % (self.prefix, self.title)

    @property
    def cover_url(self):
        return '%s%s' % (settings.MEDIA_URL, self.cover)

    @property
    def amazon_url(self):
        try:
            return 'http://www.amazon.com/dp/%s/?%s' % (self.asin, settings.AMAZON_AFFILIATE_EXTENTION)
        except:
            return 'http://www.amazon.com/dp/%s/' % self.asin


class Track(models.Model):
    """Tracks model"""
    album = models.ForeignKey(Album, blank=True, null=True, related_name='tracks')
    band = models.ForeignKey(Band, blank=True, null=True, related_name='tracks')
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    mp3 = models.FilePathField(path=settings.MEDIA_ROOT+'tracks', match='.*\.mp3$')

    class Meta:
        db_table = 'music_tracks'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('music_track_detail', None, { 'slug': self.slug })

    @property
    def mp3_url(self):
        return self.mp3.replace(settings.MEDIA_ROOT, settings.MEDIA_URL)

basic/music/views.py
from django.views.generic import list_detail
from basic.music.models import *


def genre_detail(request, slug):
  return list_detail.object_detail(
    request,
    queryset=Genre.objects.all(),
    slug=slug,
  )
genre_detail.__doc__ = list_detail.object_detail.__doc__


def genre_list(request):
  return list_detail.object_list(
    request,
    queryset=Genre.objects.all(),
    paginate_by=20,
  )
genre_list.__doc__ = list_detail.object_list.__doc__


def label_detail(request, slug):
  return list_detail.object_detail(
    request,
    queryset=Label.objects.all(),
    slug=slug,
  )
label_detail.__doc__ = list_detail.object_detail.__doc__


def label_list(request):
  return list_detail.object_list(
    request,
    queryset=Label.objects.all(),
    paginate_by=20,
  )
label_list.__doc__ = list_detail.object_list.__doc__


def band_detail(request, slug):
  return list_detail.object_detail(
    request,
    queryset=Band.objects.all(),
    slug=slug,
  )
band_detail.__doc__ = list_detail.object_detail.__doc__


def band_list(request):
  return list_detail.object_list(
    request,
    queryset=Band.objects.all(),
    paginate_by=20,
  )
band_list.__doc__ = list_detail.object_list.__doc__


def album_detail(request, slug):
  return list_detail.object_detail(
    request,
    queryset=Album.objects.all(),
    slug=slug,
  )
album_detail.__doc__ = list_detail.object_detail.__doc__


def album_list(request):
  return list_detail.object_list(
    request,
    queryset=Album.objects.all(),
    paginate_by=20,
  )
album_list.__doc__ = list_detail.object_list.__doc__


def track_detail(request, slug):
  return list_detail.object_detail(
    request,
    queryset=Track.objects.all(),
    slug=slug,
  )
track_detail.__doc__ = list_detail.object_detail.__doc__


def track_list(request):
  return list_detail.object_list(
    request,
    queryset=Track.objects.all(),
    paginate_by=20,
  )
track_list.__doc__ = list_detail.object_list.__doc__

basic/music/templates/music/_nav.html
<div id="section_nav">
  <ul class="tabs">
    <li class="music"><a href="{% url music_index %}">Music</a>
      <ul>
        <li class="genres"><a href="{% url music_genre_list %}">Genres</a></li>
        <li class="albums"><a href="{% url music_album_list %}">Albums</a></li>
        <li class="bands"><a href="{% url music_band_list %}">Bands</a></li>
        <li class="labels"><a href="{% url music_label_list %}">Labels</a></li>
        <li class="tracks"><a href="{% url music_track_list %}">Tracks</a></li>
      </ul>
    </li>
    <li class="movies"><a href="{% url movie_list %}">Movies</a></li>
    <li class="books"><a href="{% url book_list %}">Books</a></li>
  </ul>
</div>

basic/music/templates/music/album_detail.html
{% extends "music/base_music.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} music_albums{% endblock %}


{% block content_title %}
  <h2>Music Albums</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  {% load markup %}
  <h3>{{ object.full_title }}
    <em><a href="{{ object.band.get_absolute_url }}">{{ object.band.full_title }}</a></em></h3>
  
  {% if object.cover %}
  <a class="cover" href="{{ object.amazon_url }}"><img src="{{ object.cover_url }}" alt="Album cover"></a>
  {% else %}
  <div class="no_cover"></div>
  {% endif %}
  
  <ul class="info_list">
    <li>Label: <a href="{{ object.label.get_absolute_url }}">{{ object.label.full_title }}</a></li>
    <li>Released: {{ object.released|date:"d F Y" }}</li>
    <li>Genre: {% for genre in object.genre.all %}{{ genre.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    <li>ASIN: {{ object.asin }} (<a href="{{ object.amazon_url }}">Amazon</a>)</li>
  </ul>
  
  {% if object.review %}
  <div class="review">
    <h3>Review</h3>
    {{ object.review|markdown:"safe" }}
  </div>
  {% endif %}
  
  {% if object.band.album_set.all %}
  {% ifnotequal object.band.album_set.count 1 %}
  <h4>Other albums</h4>
  <ul>
    {% for album in object.band.album_set.all %}
    {% ifnotequal album object %}
    <li><a href="{{ album.get_absolute_url }}">{{ album.full_title }}</a></li>
    {% endifnotequal %}
    {% endfor %}
  </ul>
  {% endifnotequal %}
  {% endif %}
  
  {% if object.tracks.all %}
  <h4>Mp3's</h4>
  <ul>
    {% for track in object.tracks.all %}
    <li><a href="{{ track.mp3_url }}">{{ track.title }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  
{% endblock %}

basic/music/templates/music/album_list.html
{% extends "music/base_music.html" %}


{% block title %}Music Albums{% endblock %}
{% block body_class %}{{ block.super }} music_albums{% endblock %}


{% block content_title %}
  <h2>Music Albums</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <table>
    <tr>
      <th>Band</th>
      <th>Album</th>
    </tr>
  {% for album in object_list %}
    <tr class="{% cycle 'odd' 'even' %}">
      <td class="band"><a href="{{ album.band.get_absolute_url }}">{{ album.band }}</a></td>
      <td class="album"><a href="{{ album.get_absolute_url }}">{{ album.full_title }}</a></td>
    </tr>
  {% endfor %}
  </table>
{% endblock %}

basic/music/templates/music/band_detail.html
{% extends "music/base_music.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} music_bands{% endblock %}


{% block content_title %}
  <h2>Music Bands</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.full_title }} <em><a href="{{ object.website }}">Website</a></em></h3>
  
  {% if object.musicians.all %}
  <h4>Members</h4>
  <ul class="link_list">
    {% for member in object.musicians.all %}
    <li><a href="{{ member.get_absolute_url }}">{{ member.full_name }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  
  {% if object.album_set.all %}
  <h4>Albums</h4>
  <ul class="link_list">
    {% for album in object.album_set.all %}
    <li><a href="{{ album.get_absolute_url }}">{{ album.full_title }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
{% endblock %}

basic/music/templates/music/band_list.html
{% extends "music/base_music.html" %}


{% block title %}Music Bands{% endblock %}
{% block body_class %}{{ block.super }} music_bands{% endblock %}


{% block content_title %}
  <h2>Music Bands</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for band in object_list %}
    <li><a href="{{ band.get_absolute_url }}">{{ band.full_title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

basic/music/templates/music/base_music.html
{% extends "base.html" %}


{% block body_class %}music{% endblock %}

basic/music/templates/music/genre_detail.html
{% extends "music/base_music.html" %}


{% block title %}{{ object.title }}{% endblock %}
{% block body_class %}{{ block.super }} music_genres{% endblock %}


{% block content_title %}
  <h2>Music Genres</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.title }}</h3>
  <ul class="link_list">
    {% for album in object.album_set.all %}
    <li><a href="{{ album.get_absolute_url }}">{{ album.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

basic/music/templates/music/genre_list.html
{% extends "music/base_music.html" %}


{% block title %}Music Genres{% endblock %}
{% block body_class %}{{ block.super }} music_genres{% endblock %}


{% block content_title %}
  <h2>Music Genres</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for genre in object_list %}
    <li><a href="{{ genre.get_absolute_url }}">{{ genre.title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

basic/music/templates/music/index.html
{% extends "music/base_music.html" %}


{% block title %}Music{% endblock %}


{% block content_title %}
  <h2>Music</h2>
  {% include "music/_nav.html" %}
{% endblock %}

{% block content %}
  
{% endblock %}

basic/music/templates/music/label_detail.html
{% extends "music/base_music.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} music_labels{% endblock %}


{% block content_title %}
  <h2>Music Labels</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.full_title }}</h3>
  <ul class="link_list">
    {% for album in object.album_set.all %}
    <li><a href="{{ album.get_absolute_url }}">{{ album.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

basic/music/templates/music/label_list.html
{% extends "music/base_music.html" %}


{% block title %}Music Labels{% endblock %}
{% block body_class %}{{ block.super }} music_labels{% endblock %}


{% block content_title %}
  <h2>Music Labels</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for label in object_list %}
    <li><a href="{{ label.get_absolute_url }}">{{ label.full_title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

basic/music/templates/music/track_detail.html
{% extends "music/base_music.html" %}


{% block title %}{{ object.title }}{% endblock %}
{% block body_class %}{{ block.super }} music_tracks{% endblock %}


{% block content_title %}
  <h2>Music Tracks</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.title }}</h3>
  <p><a href="{{ object.mp3_url }}">Listen</a></p>
{% endblock %}

basic/music/templates/music/track_list.html
{% extends "music/base_music.html" %}


{% block title %}Music Tracks{% endblock %}
{% block body_class %}{{ block.super }} music_tracks{% endblock %}


{% block content_title %}
  <h2>Music Tracks</h2>
  {% include "music/_nav.html" %}
{% endblock %}


{% block content %}
  <table>
    <tr>
      <th>Band</th>
      <th>Album</th>
      <th>Song</th>
    </tr>
  {% for track in object_list %}
    <tr class="{% cycle 'odd' 'even' %}">
      <td class="band"><a href="{{ track.band.get_absolute_url }}">{{ track.band }}</a></td>
      <td class="album"><a href="{{ track.album.get_absolute_url }}">{{ track.album }}</a></td>
      <td><a href="{{ track.get_absolute_url }}">"{{ track.title }}"</a></td>
    </tr>
  {% endfor %}
  </table>
{% endblock %}